services:
  xiaohongshu-mcp:
    image: xpzouying/xiaohongshu-mcp
    container_name: xiaohongshu-mcp
    restart: unless-stopped
    tty: true
    volumes:
      - ./data:/app/data
    environment:
      - ROD_BROWSER_BIN=/usr/bin/chromium  # ← 无头浏览器
      - COOKIES_PATH=/app/data/cookies.json  # ← 程序读取/写入这个路径
    ports:
      - "18060:18060"